# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12bxwIhCj1aX6sxKNxyYL0oMswJs7mogx
"""

import streamlit as st
import pandas as pd
import networkx as nx
from pyvis.network import Network
import streamlit.components.v1 as components
import os

# Configuración de la página
st.set_page_config(page_title="Visor de Linaje de Datos", layout="wide")

st.title("Visualizador de Linaje de Activos")

# --- FUNCIÓN DE PROCESAMIENTO ---
def generar_html_linaje(activo_objetivo, df):
    try:
        df.columns = df.columns.str.lower().str.strip()

        # Limpieza
        for col in ['origen', 'destino', 'activo', 'tipo_activo']:
            if col in df.columns:
                df[col] = df[col].astype(str).str.strip()

        df = df[(df['origen'] != 'nan') & (df['origen'] != '') &
                (df['destino'] != 'nan') & (df['destino'] != '')]

        G_logico = nx.DiGraph()
        for _, row in df.iterrows():
            G_logico.add_edge(row['origen'], row['destino'])

        if activo_objetivo not in G_logico:
            st.error(f"Activo {activo_objetivo} no encontrado en las relaciones.")
            return None

        ancestros = nx.ancestors(G_logico, activo_objetivo)
        descendientes = nx.descendants(G_logico, activo_objetivo)
        nodos_rel = ancestros.union(descendientes).union({activo_objetivo})
        subgrafo = G_logico.subgraph(nodos_rel)

        net = Network(height='600px', width='100%', directed=True, notebook=False, cdn_resources='remote')

        colores_dict = {
            'producto': '#1B4F72', 'solucion': '#2874A6', 'dataset': '#85C1E9',
            'dominio': '#17A589', 'subdominio': '#F4D03F', 'termino negocio': '#CCD5AE',
            'servicio datos': '#A2D9CE', 'personas': '#F1948A'
        }

        for nodo in subgrafo.nodes():
            tiene_destino = len(list(G_logico.successors(nodo))) > 0
            if not tiene_destino:
                tipo_real = 'personas'
            else:
                row_info = df[df['activo'] == nodo].drop_duplicates('activo')
                if not row_info.empty:
                    tipo_real = row_info['tipo_activo'].values[0]
                else:
                    row_backup = df[(df['origen'] == nodo) | (df['destino'] == nodo)].head(1)
                    tipo_real = row_backup['tipo_activo'].values[0] if not row_backup.empty else "desconocido"

            es_obj = (nodo == activo_objetivo)
            oculto = not (es_obj or (nodo in G_logico.predecessors(activo_objetivo)))

            net.add_node(
                nodo,
                label=nodo,
                title=f"Tipo: {tipo_real}",
                color="#2175D8" if es_obj else colores_dict.get(tipo_real, '#dddddd'),
                hidden=oculto,
                size=30 if es_obj else 20
            )

        for u, v in subgrafo.edges():
            net.add_edge(u, v, color="#848484")

        net.options = {
            "physics": {"enabled": True, "stabilization": {"enabled": True, "iterations": 1000}},
            "layout": {"hierarchical": {"enabled": True, "direction": "LR", "sortMethod": "directed", "levelSeparation": 350}},
            "interaction": {"hover": True, "tooltipDelay": 200}
        }

        # Generar HTML en memoria
        html_content = net.generate_html()

        # Inyección de JS personalizado (el que ya tenías)
        css_js = """
        <style>
        .vis-loading-bar { display:none !important; }
        .btn-focus-all {
            position: fixed; top: 20px; left: 20px; z-index: 9999;
            padding: 10px 18px; background-color: #2175D8; color: white;
            border: none; border-radius: 30px; cursor: pointer; font-weight: bold;
        }
        </style>
        <script>
        network.on("stabilizationIterationsDone", function () { network.setOptions( { physics: false } ); });
        (function() {
            var btn = document.createElement('button');
            btn.innerHTML = '🔍 Re-centrar Todo';
            btn.className = 'btn-focus-all';
            document.body.appendChild(btn);
            btn.onclick = function() { network.fit({ animation: { duration: 1000 } }); };
        })();
        network.on("click", function(p) {
            if (p.nodes.length > 0) {
                var selectedNode = p.nodes[0];
                var connectedNodes = network.getConnectedNodes(selectedNode, 'to');
                connectedNodes.forEach(function(c) { nodes.update({id: c, hidden: false}); });
                setTimeout(function() { network.focus(selectedNode, { scale: 0.85, animation: { duration: 600 } }); }, 150);
            }
        });
        </script>
        """
        html_content = html_content.replace("</body>", css_js + "</body>")
        return html_content

    except Exception as e:
        st.error(f"Error procesando el grafo: {e}")
        return None

# --- INTERFAZ DE USUARIO (SIDEBAR) ---
st.sidebar.header("Configuración")
uploaded_file = st.sidebar.file_uploader("Sube tu archivo Excel (mi_linaje12.xlsx)", type=["xlsx"])

if uploaded_file:
    df_ui = pd.read_excel(uploaded_file)
    df_ui.columns = df_ui.columns.str.lower().str.strip()

    tipos = sorted(df_ui['tipo_activo'].dropna().unique().tolist())

    sel_tipo = st.sidebar.selectbox("Filtrar por Tipo:", ['TODOS'] + tipos)

    if sel_tipo == 'TODOS':
        opciones_activos = df_ui['activo'].dropna().unique()
    else:
        opciones_activos = df_ui[df_ui['tipo_activo'] == sel_tipo]['activo'].dropna().unique()

    sel_act = st.sidebar.selectbox("Selecciona Activo Objetivo:", sorted(opciones_activos))

    if st.sidebar.button("Generar Grafo"):
        with st.spinner("Generando linaje..."):
            html_grafo = generar_html_linaje(sel_act, df_ui)
            if html_grafo:
                components.html(html_grafo, height=650, scrolling=True)
else:
    st.info("Por favor, sube un archivo Excel en la barra lateral para comenzar.")
